version: "3.7"
services:

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
#    command: npm run start:dev
    command: >
      bash -c "
          npm run migrations:up &&
          npm run start:dev
      "
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
